[package]
name = "mpl-token-entangler"
version = "0.1.3"
edition = "2018"
license = "AGPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "lib"]
name = "mpl_token_entangler"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "~0.25"
anchor-spl = "~0.25"
spl-token = {version = "~3.3.0", features = ["no-entrypoint"]}
spl-associated-token-account = {version = "~1.0.5", features = ["no-entrypoint"]}
mpl-token-metadata = {path = "../../token-metadata/program", features = ["no-entrypoint"]}
thiserror = "~1.0"
arrayref = "~0.3.6"

[dev-dependencies]
solana-program-test = "~1.10.25"
solana-sdk = "~1.10.25"
